--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-03-22 23:55:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 25027)
-- Name: Tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tasks" (
    task_id integer NOT NULL,
    user_id integer NOT NULL,
    objective character varying(255) NOT NULL,
    description character varying(50),
    addition_date timestamp without time zone DEFAULT date_trunc('minute'::text, CURRENT_TIMESTAMP) NOT NULL,
    closing_date timestamp without time zone,
    finished boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Tasks" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 25025)
-- Name: Tasks_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tasks" ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tasks_task_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 25015)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    user_id integer NOT NULL,
    login character varying(50) NOT NULL,
    password text NOT NULL,
    password_salt text NOT NULL,
    addition_date timestamp without time zone DEFAULT date_trunc('minute'::text, CURRENT_TIMESTAMP) NOT NULL,
    role text DEFAULT 'user'::text NOT NULL,
    email character varying NOT NULL,
    email_confirmed boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 25013)
-- Name: Users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 25008)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3009 (class 0 OID 25027)
-- Dependencies: 204
-- Data for Name: Tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tasks" (task_id, user_id, objective, description, addition_date, closing_date, finished) FROM stdin;
2	1	Example Task #2 User #1	\N	2021-03-18 00:00:00	2021-03-26 00:00:00	f
1	1	Example Task #1 User #1	Example Description	2021-03-18 16:00:00	2021-03-24 00:00:00	t
3	1	Example Task #3 User #1	Example Description	2021-03-18 00:00:00	2021-03-24 00:00:00	t
4	1	Example Task #4 User #1	\N	2021-03-18 00:00:00	2021-03-30 00:00:00	f
5	2	Example Task #1 User #2	Example Description	2021-03-18 00:00:00	2021-03-24 00:00:00	t
6	2	Example Task #2 User #2	\N	2021-03-18 00:00:00	2021-03-30 00:00:00	f
\.


--
-- TOC entry 3007 (class 0 OID 25015)
-- Dependencies: 202
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" (user_id, login, password, password_salt, addition_date, role, email, email_confirmed) FROM stdin;
2	postgres2	Q9A/L2XTa9kOjCU2QnQ1Dt+YLGv0C7iqjsdoW04J+RkVuwbwr+Qy8ZweU+JTamVBy+WDxs1CBCovlqN+0rXDtw==	3oY�-S7���Ѽ��'�A�!NɅ\b����Oi��8�P^}g�\t\b�=´��H���\b�:X�Y	2021-03-24 00:00:00	user	test@gmail.com	t
1	postgres	HcaVRCH9ST0+WePw59Qv5ghRuB1M14a/M73xT+BPxHYVtOSkZ1MG38NnYTECfBCM0duVC4+hnNEVTXVWDPxCeg==	��K��3���I<e\t0n¼��gy�A�n*(b�Q�,1�A\b`���Q@5l��B�1����o	2021-03-24 00:00:00	admin	test@gmail.com	t
27	test1	qqNpqwCCTyN3NGJZ/fUJG3PWS3ALjVXBOgGVHjt0k3qYP43XWWsLbmUTgALEWMlMVu+vNLiZpSbg2l8iD0jROA==	��7g9ٖ�}��R��>�F�V\v�&pe�l���T϶aT�r�ͯ\f=�=��#O�:hJ��KAg	2021-03-22 23:20:00	user	majuuk91@gmail.com	t
\.


--
-- TOC entry 3005 (class 0 OID 25008)
-- Dependencies: 200
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20210318164545_InitialCreate	5.0.3
\.


--
-- TOC entry 3015 (class 0 OID 0)
-- Dependencies: 203
-- Name: Tasks_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tasks_task_id_seq"', 38, true);


--
-- TOC entry 3016 (class 0 OID 0)
-- Dependencies: 201
-- Name: Users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_user_id_seq"', 27, true);


--
-- TOC entry 2873 (class 2606 OID 25033)
-- Name: Tasks PK_Tasks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "PK_Tasks" PRIMARY KEY (task_id);


--
-- TOC entry 2870 (class 2606 OID 25024)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY (user_id);


--
-- TOC entry 2867 (class 2606 OID 25012)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2871 (class 1259 OID 25039)
-- Name: IX_Tasks_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_user_id" ON public."Tasks" USING btree (user_id);


--
-- TOC entry 2868 (class 1259 OID 25040)
-- Name: IX_Users_login; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_login" ON public."Users" USING btree (login);


--
-- TOC entry 2874 (class 2606 OID 25034)
-- Name: Tasks FK_Tasks_Users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Users_user_id" FOREIGN KEY (user_id) REFERENCES public."Users"(user_id) ON DELETE CASCADE;


-- Completed on 2021-03-22 23:55:50

--
-- PostgreSQL database dump complete
--

